name: k6 Docker Builder

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push container image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        push: true
        tags: |
           ghcr.io/metrico/k6:latest
