name: K6 Test qryn:bun
on:
  workflow_dispatch:
  
jobs:
  build:
    name: Run k6 on qryn:latest
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 8123:8123
      qryn:
        image: qxip/qryn:bun
        ports:
          - 3100:3100
        env:
          CLICKHOUSE_SERVER: clickhouse
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Download k6 for Prometheus
        run: |
          wget https://github.com/grafana/xk6-client-prometheus-remote/releases/download/v0.3.1/k6_rw_v0.3.1_linux_amd64
          chmod +x k6_rw_v0.3.1_linux_amd64
          mv k6_rw_v0.3.1_linux_amd64 k6
      - name: Run k6 local test
        run: ./k6 run --out csv=results.csv prometheus/qryn-loadtest.js 
        env:
          K6_WRITE_HOSTNAME: "localhost:3100"
          K6_READ_HOSTNAME: "localhost:3100"
          K6_WRITE_REQUEST_RATE: 1
          K6_WRITE_SERIES_PER_REQUEST: 100
          K6_READ_REQUEST_RATE: 1
          K6_DURATION_MIN: 1
          RAMP_UP_MIN: 0
      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: results.csv
