name: K6 Prometheus qryn:latest
on:
  workflow_dispatch:
    inputs:
      qryn_tag:
        description: 'Build/Tag for qryn (latest)'
        required: false
      clickhouse_tag:
        description: 'BuildTag for ClickHouse (latest)'
        required: false

jobs:
  build:
    name: Run k6 on qryn:latest
    runs-on: ubuntu-latest
    env:
      QRYN_VERSION: "clickhouse/clickhouse-server:${{ github.event.inputs.qryn_tag || 'latest' }}"
      CLICKHOUSE_VERSION: "qxip/qryn:${{ github.event.inputs.clickhouse_tag || 'latest' }}"
    services:
      clickhouse:
        image: "clickhouse/clickhouse-server:${{ github.event.inputs.qryn_tag || 'latest' }}"
        ports:
          - 8123:8123
      qryn:
        image:  "qxip/qryn:${{ github.event.inputs.clickhouse_tag || 'latest' }}"
        ports:
          - 3100:3100
        env:
          CLICKHOUSE_SERVER: clickhouse
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Download k6 for Prometheus
        run: |
          wget https://github.com/metrico/qryn-bench/releases/download/latest/k6
          chmod +x k6
      - name: Run k6 local test
        run: ./k6 run --out csv=results.csv prometheus/qryn-loadtest.js 
        env:
          K6_WRITE_HOSTNAME: "localhost:3100"
          K6_READ_HOSTNAME: "localhost:3100"
          K6_WRITE_REQUEST_RATE: 1
          K6_WRITE_SERIES_PER_REQUEST: 100
          K6_READ_REQUEST_RATE: 1
          K6_DURATION_MIN: 1
          RAMP_UP_MIN: 0
      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
             results.csv
             summary.html
      - name: Convert HTML to Markdown
        id: html2markdown
        uses: rknj/html2markdown@v0.1.0
        with:
          html-file: "summary.html"
      - name: Summary Report
        run: |
          echo "${{ steps.html2markdown.outputs.markdown-content }}" >> $GITHUB_STEP_SUMMARY
