name: K6 Loki Test qryn:latest
on:
  workflow_dispatch:
  
jobs:
  build:
    name: Run k6 on qryn:latest
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 8123:8123
      qryn:
        image: qxip/qryn:latest
        ports:
          - 3100:3100
        env:
          CLICKHOUSE_SERVER: clickhouse
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Download k6 for Prometheus
        run: |
          wget https://github.com/metrico/qryn-bench/releases/download/latest/k6
          chmod +x k6
      - name: Run k6 loki test
        run: ./k6 run --out csv=results.csv loki/qryn-loki-loadtest.js 
      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: results.csv
