name: K6 Test
on:
  workflow_dispatch:
  
jobs:
  build:
    name: Run k6 on qryn:latest
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 8123:8123
      qryn:
        image: qxip/qryn:latest
        ports:
          - 3100:3100
        env:
          CLICKHOUSE_SERVER: clickhouse
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go install go.k6.io/xk6/cmd/xk6@latest
      - run: xk6 build --with github.com/grafana/xk6-client-prometheus-remote@latest
      - name: Run k6 local test
        run: k6 run --duration 10s qryn-loadtest.js 
        env:
          K6_WRITE_HOSTNAME: "qryn:3100"
          K6_READ_HOSTNAME: "qryn:3100"
          K6_WRITE_REQUEST_RATE: 1
          K6_WRITE_SERIES_PER_REQUEST: 100
          K6_READ_REQUEST_RATE: 1
          RAMP_UP_MIN: 0
